Travis: resvole boulder to 127.0.0.1
Should fix the following:

```
ConnectionError: HTTPConnectionPool(host='boulder', port=4001): Max retries exceeded with url: /terms/v1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x32f3710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```